import type { Metadata } from "next";
import "./styles/globals.scss";
import { AuthProvider } from "./providers/AuthProvider";

export const metadata: Metadata = {
  title: "Vmeste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
